### ISSUE TITLE
Issue while creating endpoint

### ISSUE THREAD

**Issue by RajarshiBhadra** [aws-samples/sagemaker-byo-catboost-container-demo#1]
Hi,

I followed your steps and was able to create a custom training job in catbost. However when I try to deploy it I get the following error as I can see in cloud watch metrices

exec: "serve": executable file not found in $PATH

Any Idea what might be going wrong?

**Comment by danshah** [comment]
Hi RajarshiBhadra. I receive an issue when deploying as well. Were you ever able to deploy a catboost model to SageMaker?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-114-2473e845de98> in <module>
----> 1 my_predictor = catboost.deploy(initial_instance_count = 1, instance_type = 'ml.m4.xlarge')

~/opt/anaconda3/lib/python3.8/site-packages/sagemaker/estimator.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, use_compiled_model, wait, model_name, kms_key, data_capture_config, tags, **kwargs)
    916             model = self.create_model(**kwargs)
    917 
--> 918         model.name = model_name
    919 
    920         return model.deploy(

AttributeError: 'NoneType' object has no attribute 'name'

**Comment by la-cruche** [comment]
Hi sorry for late reply, this demo sample is for training only, it does not support serving. If you want to deploy Catboost on a SageMaker endpoint, you can try either:

- using the [existing container and SDK we have for the Scikit ecosystem](https://sagemaker.readthedocs.io/en/stable/frameworks/sklearn/using_sklearn.html#sagemaker-scikit-learn-model-server) (bringing your dependencies via requirements.txt)
- or create a custom docker with your own server and inference code, following the [SageMaker specification. ](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-inference-code.html)
